// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/calculator/v1/calculator.proto

package calculatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation type enum
type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_ADD         Operation = 1
	Operation_OPERATION_SUBTRACT    Operation = 2
	Operation_OPERATION_MULTIPLY    Operation = 3
	Operation_OPERATION_DIVIDE      Operation = 4
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_ADD",
		2: "OPERATION_SUBTRACT",
		3: "OPERATION_MULTIPLY",
		4: "OPERATION_DIVIDE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_ADD":         1,
		"OPERATION_SUBTRACT":    2,
		"OPERATION_MULTIPLY":    3,
		"OPERATION_DIVIDE":      4,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_calculator_v1_calculator_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_calculator_v1_calculator_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

// Request message for Calculate
type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstOperand  float64                `protobuf:"fixed64,1,opt,name=first_operand,json=firstOperand,proto3" json:"first_operand,omitempty"`
	SecondOperand float64                `protobuf:"fixed64,2,opt,name=second_operand,json=secondOperand,proto3" json:"second_operand,omitempty"`
	Operation     Operation              `protobuf:"varint,3,opt,name=operation,proto3,enum=calculator.v1.Operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetFirstOperand() float64 {
	if x != nil {
		return x.FirstOperand
	}
	return 0
}

func (x *CalculateRequest) GetSecondOperand() float64 {
	if x != nil {
		return x.SecondOperand
	}
	return 0
}

func (x *CalculateRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

// Response message for Calculate
type CalculateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if any (e.g., division by zero)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CalculateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"$proto/calculator/v1/calculator.proto\x12\rcalculator.v1\"\x96\x01\n" +
	"\x10CalculateRequest\x12#\n" +
	"\rfirst_operand\x18\x01 \x01(\x01R\ffirstOperand\x12%\n" +
	"\x0esecond_operand\x18\x02 \x01(\x01R\rsecondOperand\x126\n" +
	"\toperation\x18\x03 \x01(\x0e2\x18.calculator.v1.OperationR\toperation\"A\n" +
	"\x11CalculateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\x7f\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOPERATION_ADD\x10\x01\x12\x16\n" +
	"\x12OPERATION_SUBTRACT\x10\x02\x12\x16\n" +
	"\x12OPERATION_MULTIPLY\x10\x03\x12\x14\n" +
	"\x10OPERATION_DIVIDE\x10\x042e\n" +
	"\x11CalculatorService\x12P\n" +
	"\tCalculate\x12\x1f.calculator.v1.CalculateRequest\x1a .calculator.v1.CalculateResponse\"\x00B%Z#calculator/backend/api/calculatorv1b\x06proto3"

var (
	file_proto_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_v1_calculator_proto_rawDescData []byte
)

func file_proto_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_v1_calculator_proto_rawDesc), len(file_proto_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_v1_calculator_proto_rawDescData
}

var file_proto_calculator_v1_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calculator_v1_calculator_proto_goTypes = []any{
	(Operation)(0),            // 0: calculator.v1.Operation
	(*CalculateRequest)(nil),  // 1: calculator.v1.CalculateRequest
	(*CalculateResponse)(nil), // 2: calculator.v1.CalculateResponse
}
var file_proto_calculator_v1_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.v1.CalculateRequest.operation:type_name -> calculator.v1.Operation
	1, // 1: calculator.v1.CalculatorService.Calculate:input_type -> calculator.v1.CalculateRequest
	2, // 2: calculator.v1.CalculatorService.Calculate:output_type -> calculator.v1.CalculateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calculator_v1_calculator_proto_init() }
func file_proto_calculator_v1_calculator_proto_init() {
	if File_proto_calculator_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_v1_calculator_proto_rawDesc), len(file_proto_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_v1_calculator_proto_depIdxs,
		EnumInfos:         file_proto_calculator_v1_calculator_proto_enumTypes,
		MessageInfos:      file_proto_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_v1_calculator_proto = out.File
	file_proto_calculator_v1_calculator_proto_goTypes = nil
	file_proto_calculator_v1_calculator_proto_depIdxs = nil
}
